SRC	= 	$(wildcard src/*.c) \
		$(wildcard test/*.c) \
		$(wildcard lib/unity/*.c)

OBJ = $(SRC:.c=.o)

TARGET = test_conio

DEP = $(OBJ:.o=.d)

CFLAGS =  -I. -I./lib/unity -I./src
CFLAGS += -std=c99 -pedantic -Wall -Wextra -Werror

LDFLAGS = -lm

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

.PHONY:	clean run 

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(OBJ) $(TARGET)
